{% set name = "kxmlgui" %}
{% set version = "5.68.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kxmlgui-{{ version }}.tar.xz
  sha256: 6310e9a725a982d3b70672367c5858727437fe08c8e409458e48b6015c7bf10e

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kxmlgui', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - attica
    - ki18n
    - kcoreaddons
    - kitemviews
    - kconfig
    - kglobalaccel
    - kconfigwidgets
    - kiconthemes
    - ktextwidgets
    - kwindowsystem
    - kwidgetsaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5XmlGui.so

about:
  home: https://api.kde.org/frameworks/kxmlgui/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Framework for managing menu and toolbar actions
  description: |
    KXMLGUI provides a framework for managing menu and toolbar actions
    in an abstract way. The actions are configured through a XML description
    and hooks in the application code. The framework supports merging of
    multiple description for example for integrating actions from plugins.
  dev_url: https://cgit.kde.org/kxmlgui.git/tree

extra:
  recipe-maintainers:
    - scopatz
