{% set name = "kxmlgui" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kxmlgui-{{ version }}.tar.xz
  sha256: c5601a811c5d680b370ccf0388de71a49af090718b5f25716c38ce9689c783a1

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kxmlgui', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - attica >={{ version }}
    - ki18n >={{ version }}
    - kcoreaddons >={{ version }}
    - kitemviews >={{ version }}
    - kconfig >={{ version }}
    - kglobalaccel >={{ version }}
    - kconfigwidgets >={{ version }}
    - kiconthemes >={{ version }}
    - ktextwidgets >={{ version }}
    - kwindowsystem >={{ version }}
    - kwidgetsaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5XmlGui.so

about:
  home: https://api.kde.org/frameworks/kxmlgui/html/index.html
  license: GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Framework for managing menu and toolbar actions
  description: |
    KXMLGUI provides a framework for managing menu and toolbar actions
    in an abstract way. The actions are configured through a XML description
    and hooks in the application code. The framework supports merging of
    multiple description for example for integrating actions from plugins.
  dev_url: https://cgit.kde.org/kxmlgui.git/tree

extra:
  recipe-maintainers:
    - scopatz
